# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

set nofixendofline

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
run '~/.tmux/plugins/tpm/tpm'

# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on
set -g default-terminal "tmux-256color"

set -g @catppuccin_flavor "mocha"

set -g status-position top
set -g status-left ''
set -g status-right "#{E:@catppuccin_status_application} #{E:@catppuccin_status_uptime}"

set -g @catpuccin_status_right "basic"
set -g @catppuccin_window_status_style "custom"

set -g @catppuccin_window_default_text " #{window_name}"
set -g @catppuccin_window_status "icon"
set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_number_position "left"

set -g @catppuccin_window_left_separator " "
set -g @catppuccin_window_middle_separator " "
set -g @catppuccin_window_right_separator " "

## Window current configuration
set -g @catppuccin_window_current_text " #{window_name}"
set -g @catppuccin_window_current_fill "all"

run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

# don't do anything when a 'bell' rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none
