experimental-features = nix-command flakes
min-free = 10G
max-free = 30G
auto-optimise-store = true
keep-outputs = false
keep-derivations = false
builders-use-substitutes = true
extra-substituters = https://nix-community.cachix.org
extra-trusted-public-keys = nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=
